---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: bluexp ransomware protection, ransomware protection prerequisites, resilience 
summary: 通过验证对您的环境、网络访问、登录和 Web 浏览器的支持，开始使用NetApp Ransomware Resilience。 
---
= NetApp Ransomware Resilience前提条件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
为了确保 NetApp Ransomware Resilience 的成功部署，请验证您的操作环境、网络访问和 Web 浏览器的准备情况。

检查并确保您满足以下要求。



== 支持的系统

请确保您使用的是受支持的系统：

|===
| 环境 | 协议 | 支持的版本 


| Amazon FSx for NetApp ONTAP* | CIFS、NFS 和 SAN | 不适用 


| Azure NetApp Files | CIFS 和 NFS | 不适用 


.2+| 适用于 AWS 的Cloud Volumes ONTAP | CIFS 和 NFS | 9.11.1 及更高版本 


| SAN（FC、iSCSI 和 NVMe） | 9.17.1 及更高版本 


.2+| 适用于 Google Cloud Platform 的Cloud Volumes ONTAP | CIFS 和 NFS | 9.11.1 及更高版本 


| SAN（FC、iSCSI 和 NVMe） | 9.17.1 及更高版本 


.2+| 适用于 Microsoft Azure 的Cloud Volumes ONTAP | CIFS 和 NFS | 9.12.1 及更高版本 


| SAN（FC、iSCSI 和 NVMe） | 9.17.1 及更高版本 


.2+| ONTAP （本地部署） | CIFS 和 NFS | 9.11.1 及更高版本 


| SAN（FC、iSCSI 和 NVMe） | 9.17.1 及更高版本 
|===
{asterisk} Amazon FSx for NetApp ONTAP使用自主勒索软件保护 (ARP) 而不是 ARP/AI。有关两者区别的更多信息，请参阅link:https://docs.netapp.com/us-en/ontap/anti-ransomware/#arp-ai["ARP/AI"^]。



== NetApp Console要求

您的NetApp Console配置需要：

* 具有组织管理员权限的NetApp Console用户帐户，用于发现资源。
* 一个控制台组织和系统，其中至少有一个活动的控制台代理连接到link:concept-ransomware-resilience.html#supported-backup-targets-systems-and-workload-data-sources["支持的系统"]。
+
** 如果您的本地ONTAP集群或 AWS 或 Azure 云中的Cloud Volumes ONTAP未在控制台中设置，请参阅link:https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["了解如何配置控制台代理"^]和link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["标准控制台要求"^]。
+

NOTE: 如果您在单个控制台组织中拥有多个控制台代理，则勒索软件恢复功能将扫描除控制台 UI 中当前选择的代理之外的所有控制台代理中的ONTAP资源。



* 控制台代理必须具有 `cloudmanager-ransomware-protection`容器处于活动状态。
* 至少一个具有NetApp本地ONTAP集群或 AWS 或 Azure 中的Cloud Volumes ONTAP 的控制台系统。勒索软件恢复支持 NAS（NFS 和 SMB）和 SAN（iSCSI、FC 和 NVMe）协议。
+
** ONTAP或Cloud Volumes ONTAP集群（ ONTAP版本 9.11.1 或更高版本）支持勒索软件恢复功能。
+

NOTE: 要在 SAN 工作负载上使用勒索软件恢复功能，您必须运行ONTAP 9.17.1 或更高版本。







== ONTAP 要求

* 您必须运行ONTAP 9.11.1 或更高版本，并且在本地ONTAP实例上启用ONTAP One 许可证。有关ONTAP支持的更多信息，请参阅link:https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["自主勒索软件防护概述"^]。
* 要应用保护配置（例如启用自主勒索软件保护），勒索软件恢复能力需要ONTAP集群上的管理员权限。ONTAP集群应该仅使用ONTAP集群管理员用户凭据进行加入。



NOTE: 如果您已使用非管理员凭据将ONTAP集群连接到控制台，则[您必须更新ONTAP集群中的凭据](#update-non-admin-user-permissions-in-an-ontap-system)。



== 数据备份

* 在NetApp StorageGRID、AWS S3、Azure Blob 或 Google Cloud Platform 中拥有一个帐户，用于备份目标，并配置了适当的访问权限。
+
请参阅 https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["AWS、Azure 或 S3 权限列表"^]了解详情。

* 不需要在系统上启用NetApp Backup and Recovery 。
+
勒索软件恢复力有助于通过设置选项配置备份目标。看link:rp-use-settings.html["配置设置"] 。





== 可疑用户行为要求

要使 Ransomware Resilience 提供有关可疑用户行为的警报，必须配置用户活动代理。要安装用户活动代理，请确保您的系统满足 link:reference-user-activity-requirements.html["要求"]。



== 更新ONTAP系统中的非管理员用户权限

如果需要更新特定系统的非管理员用户权限，请使用此过程步骤。

. 登录到 Console。在仪表板中，确定需要更新其 ONTAP 用户权限的系统。
. 选择系统以查看其详细信息。
. 选择“查看其他信息”以显示用户名。
. 以管理员用户身份登录ONTAP集群 CLI。
. 显示该用户的现有角色：
+
[listing]
----
security login show -user-or-group-name <username>
----
. 更改用户的角色。进入：
+
[listing]
----
security login modify -user-or-group-name <username> -application console|http|ontapi|ssh|telnet -authentication-method password -role admin
----
. 返回NetApp Console以使用勒索软件恢复功能。

