---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: 查找有关NetApp Ransomware Resilience的常见问题的答案。 
---
= NetApp Ransomware Resilience 常见问题解答
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
使用此常见问题解答快速了解有关 NetApp Ransomware Resilience 的问题。



[[deployment]]
== 部署

.使用勒索软件恢复功能需要许可证吗？
您可以使用以下许可证类型：

* 注册即可获得 30 天免费试用。
* 通过 Amazon Web Services (AWS) Marketplace、Google Cloud Marketplace 和 Microsoft Azure Marketplace 购买NetApp Intelligent Services和勒索软件恢复的即用即付 (PAYGO) 订阅。
* 自带许可证 (BYOL)，即您从NetApp销售代表处获得的NetApp许可证文件 (NLF)。您可以使用许可证序列号在控制台的“Licenses and subscriptions”部分激活 BYOL。


.如何启用勒索软件防御能力？
您可以从 NetApp Console 访问 Ransomware Resilience。请确保您拥有所需的link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-roles.html["访问角色"]并符合link:rp-start-prerequisites.html["前提条件"]。如果已成功配置 Console 代理，则可以link:rp-start-discover.html["发现工作负载"]。

有关详细信息，请参阅link:rp-start-login.html["访问勒索软件弹性"]和link:rp-start-quick-start.html["勒索软件抵御能力快速入门指南"]。

.勒索软件防护是否提供标准模式、受限模式和私有模式？
勒索软件恢复功能目前仅在标准模式下可用。

有关所有NetApp数据服务中这些模式的说明，请参阅 https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["NetApp Console部署模式"^]。

.Ransomware Resilience 的计费是如何运作的？
您可以免费试用 Ransomware Resilience 30 天。NetApp不会向您收取使用 Ransomware Resilience 试用版的费用。

如果您同时拥有备份和恢复以及勒索软件恢复功能，则受这两种产品保护的任何公共数据仅由勒索软件恢复功能计费。

当工作负载被归类为受保护时，它将计入购买的容量或 PAYGO 订阅。当启用加密或用户活动检测策略时，Ransomware Resilience 会将工作负载分类为受保护。如果没有这些检测策略中的至少一个，工作负载将被归类为存在风险。存在风险的工作负载不计入购买的容量。

在免费试用期结束后，受保护的工作负载将计入购买的容量或订阅。Ransomware Resilience 对于与受保护工作负载相关的数据（由 ONTAP 报告），在效率优化之前按 GB 收费。

在考虑规模调整时，无论数据位于热存储层还是冷存储层，许可成本均基于活动文件系统的逻辑容量。快照消耗的空间不包含在此计算中，即使这些快照存储在冷层中也不例外。

.试用期结束或许可证到期后会发生什么？
免费试用期结束或许可证或订阅到期后，除非您将其排除在外，否则工作负载在 Ransomware Resilience 上仍然可见。使用过期的许可证或试用版，您可以：

* 查看工作负载和工作负载健康状况
* 删除策略等资源
* 运行在试用期间或许可证下创建的所有计划操作


要停用 Ransomware Resilience，请提交支持请求。请求必须包含您的组织 ID，并注明您要停用该服务。



[[access]]
== 使用权

.勒索软件恢复能力网址是什么？
在浏览器中输入 https://console.netapp.com/["https://console.netapp.com/ransomware-resilience"^] 访问控制台。

.访问权限是如何管理的？
https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["了解所有服务的控制台访问角色"^]。勒索软件恢复能力也具备 link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-ransomware-roles.html["专用访问角色"^]。

.哪种设备分辨率最佳？
勒索软件恢复的推荐设备分辨率为 1920x1080 或更高。

.我应该使用哪个浏览器？
您可以使用任何现代网络浏览器访问NetApp Console。



[[interoperability]]
== 互操作性

.Ransomware Resilience 是否了解ONTAP中的保护设置？
是的，Ransomware Resilience 发现了在ONTAP中设置的快照计划。

.勒索软件弹性如何与 NetApp Backup and Recovery 交互？
Ransomware Resilience 与 Backup and Recovery 配合使用，发现并设置文件共享工作负载的快照和备份策略。Ransomware Resilience 还与 Backup and Recovery 配合使用，以执行文件和工作负载一致的恢复。

对于许可和计费，即使您没有单独的备份和恢复许可证，勒索软件恢复功能也可以与备份和恢复功能集成。如果您同时拥有备份和恢复以及勒索软件恢复功能，则受这两种产品保护的任何公共数据仅由勒索软件恢复功能计费。



[[workloads]]
== 工作负载

.在勒索软件防御的语境下，什么是工作负载？
工作负载是 VM 或文件共享。

.勒索软件恢复能力如何确定工作负载数据的优先级？
工作负载优先级（关键、标准、重要）由已应用于与工作负载关联的每个卷的快照频率和计划备份决定。

link:rp-use-protect.html["了解工作负载优先级或重要性"] 。

.勒索软件恢复能力支持哪些工作负载？
勒索软件恢复能力可以识别以下工作负载：Oracle、文件共享、块存储、虚拟机和虚拟机数据存储。

.如何将数据与工作负载关联起来？
勒索软件恢复能力会发现卷和文件扩展名，并将它们与相应的工作负载关联起来。

.什么是受保护的工作负载？
在 Ransomware Resilience 中，当启用 _detection_ 策略时，工作负载显示 *protected* 状态。检测策略必须由加密检测或可疑用户行为检测（或两者）组成。有关详细信息，请参见 link:rp-use-protect.html#add-a-ransomware-protection-strategy["检测策略"]。

.什么是“高风险”工作量？
工作负载必须具有启用了加密检测或用户行为检测的勒索软件保护策略，才能被视为受保护。如果没有这些检测策略中的至少一种，则工作负载将被标记为存在风险。如果工作负载具有备份或快照策略，但未启用加密检测或用户行为检测，则该工作负载将被视为存在风险。

Ransomware Resilience 还提供可疑文件扩展名检测。如果可疑文件扩展名检测是唯一启用的检测策略，则工作负载将被标记为存在风险。

为了防范勒索软件，您应该启用 link:rp-use-protect.html#add-a-ransomware-protection-strategy["检测策略"]。

.我添加了一个新卷，但它还没有显示出来。我应该怎么办？
如果您向环境中添加了新卷，请重新启动工作负载发现。在发现体积之后， link:rp-use-protect.html#add-a-ransomware-protection-strategy["采取保护策略以保护新增容量"]。



[[protection-policies]]
== 保护策略

.勒索软件恢复策略是否可以与其他类型的工作负载策略共存？
目前，备份和恢复（云备份）支持每个卷一个备份策略。如果您使用备份和恢复功能配置备份保护，它将与勒索软件恢复功能共享备份策略。

快照副本不受限制，可以从每个服务单独添加。

.勒索软件防护策略需要哪些策略？
一个 link:rp-use-protect.html#add-a-ransomware-protection-strategy["勒索软件防护策略"] 需要：

* 勒索软件检测策略，以及
* 快照策略


勒索软件抵御策略中不需要备份策略。

.Ransomware Resilience 可以识别哪些类型的攻击？
Ransomware Resilience 可识别五种攻击类型：

* 加密（熵）
* 加密（用户行为）
* 数据泄露
* 数据销毁
* 可疑的用户活动


详细了解link:concept-ransomware-resilience.html#attack-types["攻击类型"]。

.Ransomware Resilience 是否了解ONTAP中的保护设置？
是的，Ransomware Resilience 会发现在 ONTAP 中设置的快照计划。它还会发现是否在发现的工作负载中的所有卷上启用了 ARP 和 FPolicy。您在 Ransomware Resilience 控制面板中看到的信息是从其他 NetApp 解决方案和产品中汇总而来的。

.Ransomware Resilience 是否了解 Backup and Recovery 中已经制定的策略？
是的，如果您在 Backup and Recovery 中管理工作负载，则由这些产品管理的策略将被纳入 Ransomware Resilience。

.是否可以修改从 NetApp Backup and Recovery 结转的策略？
不可以，您无法修改由 Backup and Recovery from Ransomware Resilience 管理的策略。您可以在 Backup and Recovery 中管理对这些策略的任何更改。

.如果ONTAP中存在策略（例如 ARP、FPolicy 和快照），这些策略是否会在勒索软件恢复功能中更改？
不会。勒索软件恢复不会修改ONTAP中的任何现有检测策略（ARP、FPolicy 设置）。

.注册 Ransomware Resilience 后，如果在 Backup and Recovery 中添加新策略，会发生什么情况？
Ransomware Resilience 可识别 Backup and Recovery 中新创建的策略和策略更改。

.能否通过ONTAP更改策略？
是的，您可以在 Ransomware Resilience 中从ONTAP更改策略。您还可以在勒索软件恢复中创建新策略并将其应用于工作负载。此操作将用在勒索软件恢复中创建的策略替换现有的ONTAP策略。

.可以在ONTAP中禁用策略吗？
您可以使用ONTAP中的系统管理器 UI、API 或 CLI 在检测策略中禁用 ARP。

您可以通过应用不包含 FPolicy 和备份策略的其他策略来禁用它们。
