---
sidebar: sidebar 
permalink: rp-start-setup.html 
keywords: bluexp, ransomware protection, aws, azure 
summary: 要使用勒索软件恢复能力，请执行几个步骤进行设置。 
---
= 设置NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
通过准备备份目标、查看先决条件以及配置 NetApp Console 和 Console 代理来设置 NetApp Ransomware Resilience。



[[prepare-the-backup-destination]]
== 准备备份目标

准备以下备份目标之一：

* NetAppStorageGRID
* Amazon Web Services
* Google Cloud Platform
* Microsoft Azure


在备份目标本身中配置选项后，您稍后将在 Ransomware Resilience 中将其配置为备份目标。有关如何在 Ransomware Resilience 中配置备份目标的详细信息，请参阅 link:task-backup-destination.html["配置备份目标"]。



[[prepare-storagegrid-to-become-a-backup-destination]]
=== 准备StorageGRID以成为备份目标

如果要使用StorageGRID作为备份目标，请参阅 https://docs.netapp.com/us-en/storagegrid-117/index.html["StorageGRID文档"^]有关StorageGRID的详细信息。



[[prepare-aws-to-become-a-backup-destination]]
=== 准备 AWS 成为备份目标

* 在 AWS 中设置一个帐户。
* 配置 https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["AWS 权限"^]在 AWS 中。


有关在控制台中管理 AWS 存储的详细信息，请参阅 https://docs.netapp.com/us-en/console-setup-admin/task-viewing-amazon-s3.html["管理您的 Amazon S3 存储桶"^]。



[[prepare-azure-to-become-a-backup-destination]]
=== 准备 Azure 以成为备份目标

* 在 Azure 中设置一个帐户。
* 配置 https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Azure 权限"^]在 Azure 中。


有关在控制台中管理 Azure 存储的详细信息，请参阅 https://docs.netapp.com/us-en/storage-management-blob-storage/task-view-azure-blob-storage.html["管理 Azure 存储帐户"^]。



[[set-up-the-netapp-console]]
== 设置NetApp Console

下一步是设置 NetApp Console 和 Ransomware Resilience。

审查 https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["标准模式的控制台要求"^]。



[[create-a-console-agent]]
=== 创建控制台代理

请联系您的 NetApp 销售代表以尝试或使用此服务。然后，Console 代理将包含 Ransomware Resilience 所需的功能。

要为 Ransomware Resilience 创建 Console 代理，请联系有权创建 Console 代理的 Console 组织管理员，并参阅 https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["如何创建控制台代理"^]。


NOTE: 如果有多个 Console 代理，Ransomware Resilience 会扫描所有 Console 代理的数据，而不仅仅是 Console 中当前显示的数据。该服务扫描与组织关联的所有项目和 Console 代理的数据。
