---
sidebar: sidebar 
permalink: troubleshoot-user-activity.html 
keywords: user activity detection, troubleshoot 
summary: 如果您在 NetApp Ransomware Resilience 中安装用户活动代理时遇到问题，请查看以下常见方案和解决方案。 
---
= 对 NetApp Ransomware Resilience 中的用户活动代理问题进行故障排除
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
如果您在 NetApp Ransomware Resilience 中安装或运行用户活动代理时遇到问题，请查看以下常见方案和解决方案。



[[installation-issues]]
== 安装问题

[cols="20,80"]
|===


| 问题描述 | 解决方法 


| 用户活动代理安装无法创建 /opt/netapp/cloudsecure/agent/logs/agent.log 文件夹，且 install.log 文件未提供相关信息。 | 此错误发生在代理的引导过程中。该错误未记录在日志文件中，因为它发生在初始化之前。该错误被重定向到标准输出。使用命令 `journalctl -u cloudsecure-agent.service`查看错误。 


| 用户活动代理安装失败，错误为"不支持此 Linux 发行版。正在退出安装。" | 此错误表示您的系统不符合系统要求。在尝试安装之前，请查看系统要求并进行任何必要的更新。 


| 用户活动代理安装失败，错误为"-bash: unzip: command not found." | 请确保已安装 unzip；如果已安装 Yum，请运行 `yum install unzip`以安装 unzip。然后，再次尝试安装。 


| 用户活动代理 VM 位于 Zscaler 代理后面，安装失败。 | 在 Zscaler 代理中禁用 *.cloudinsights.netapp.com URL 的 SSL 检查。 


| 安装代理时，解压后安装挂起。 | 如果在代理安装期间 `chmod 755 -Rf`命令失败，则该命令由非根 `sudo`用户运行，其工作目录中的文件属于其他用户，并且无法更改权限。因此，安装失败。要解决此问题，请创建一个名为"cloudsecure"的新目录，输入该目录，复制并粘贴完整 `token=... ./cloudsecure-agent-install.sh`安装命令，然后按 Enter 键。安装应继续进行。如果安装仍然失败，请打开支持案例。 


| cloudsecure-agent-symptom-collector.sh 脚本失败，错误为"ERROR: Failed to create /tmp/cloudsecure-agent-symptoms.zip" | 使用命令 `yum install zip`安装 zip 工具，然后再次运行 `cloudsecure-agent-symptom-collector.sh`。 


| 用户活动代理安装失败，错误为"useradd: cannot create directory /home/cssys." | 由于权限错误，无法在 /home 目录下创建用户的登录目录。使用命令 `sudo useradd <user_name> -m -d HOME_DIR`创建 cssys 用户并手动添加其登录目录。在此命令中， `-m`用于在主目录不存在时创建主目录； `-d`将 HOME_DIR 指定为登录目录。 
|===


[[post-installation-issues]]
== 安装后问题

[cols="20,80"]
|===


| 问题描述 | 解决方法 


 a| 
安装后用户活动代理未运行。运行命令 `systemctl status cloudsecure-agent.service`后，输出显示：

[source]
----
[root@demo ~]# systemctl status cloudsecure-agent.service +
agent.service - Workload Security Agent Daemon Service
Loaded: loaded (/usr/lib/systemd/system/cloudsecure-agent.service; enabled; vendor preset: disabled) +
Active: activating (auto-restart) (Result: exit-code) since Tue 2021-08-03 21:12:26 PDT; 2s ago +
Process: 25889 ExecStart=/bin/bash /opt/netapp/cloudsecure/agent/bin/cloudsecure-agent (code=exited status=126) +
Main PID: 25889 (code=exited, status=126), +
Aug 03 21:12:26 demo systemd[1]: cloudsecure-agent.service: main process exited, code=exited, status=126/n/a +
Aug 03 21:12:26 demo systemd[1]: Unit cloudsecure-agent.serve
---- a| 
如果 /opt/netapp 是 NFS 挂载，并且 cssys 用户没有此文件夹的访问权限，则安装将失败。用户 cssys 是由用户活动代理安装程序创建的本地用户，可能没有访问已挂载共享的权限。

您可以通过尝试使用 cssys 用户访问 `/opt/netapp/cloudsecure/agent/bin/cloudsecure-agent`来检查权限。如果返回"Permission denied"，则表示尚未设置相应的权限。安装在计算机的本地目录上，而不是挂载的文件夹上。



| 代理已通过代理服务器连接，但自安装以来代理服务器已更改。如何更改代理配置？  a| 
编辑 agent.properties 代理设置：

.步骤
. 更改为包含属性文件的文件夹： `cd /opt/netapp/cloudsecure/conf`
. 在文本编辑器中打开 agent.properties 文件。
. 添加或修改以下行：
+
[source]
----
AGENT_PROXY_HOST=<proxy.vm.url> +
AGENT_PROXY_PORT=<portValue> +
AGENT_PROXY_USER=<user> +
AGENT_PROXY_PASSWORD=<password>
----
. 保存文件。
. 重新启动代理： `sudo systemctl restart cloudsecure-agent.service`。




| 代理已成功安装并正在运行，但已意外停止。  a| 
.步骤
. 通过 SSH 在代理计算机上进行身份验证，以检查服务的状态。通过 `sudo systemctl status cloudsecure-agent.service`检查代理服务的状态。
. 检查日志中是否有消息"Failed to start Workload Security daemon service."
. 检查 cssys 用户是否存在于用户活动代理计算机上。执行以下命令分别检查 cssys 用户和组是否存在： `sudo id cssys` then `sudo groups cssys`。
. 如果该用户或组不存在，则可能是集中式监控策略删除了 cssys 用户。通过执行以下命令手动创建 cssys 用户和组： `sudo useradd cssys` then `sudo groupadd cssys`。
. 重新启动代理服务： `sudo systemctl restart cloudsecure-agent.service`。




| 此用户活动代理状态未连接 | 重新启动代理。通过 SSH 向用户活动代理计算机进行身份验证，然后使用命令 `sudo systemctl restart cloudsecure-agent.service`重新启动代理。重新启动后，使用命令 `sudo systemctl status cloudsecure-agent.service`检查代理的状态。如果重新启动操作成功，则输出显示"CONNECTED" 
|===