= 来自Digital Advisor的安全风险评估
:allow-uri-read: 




[[security-risk-assessment-from-digital-advisor]]
=== 来自Digital Advisor的安全风险评估

BlueXP 勒索软件防护现在从 NetApp Digital Advisor 收集有关高危和严重集群安全风险的信息。如果发现风险，BlueXP 勒索软件防护会在仪表板的*建议操作*窗格中显示以下建议："修复集群 <name> 上的已知安全漏洞。"从仪表板建议中，选择*查看并修复*以查看 Digital Advisor 和相关的常见漏洞与披露 (CVE) 文章。如果存在多个安全风险，请在 Digital Advisor 中查看详细信息。

参考 https://docs.netapp.com/us-en/active-iq/index.html["Digital Advisor文档"^]。



[[back-up-to-google-cloud-platform]]
=== 备份到 Google Cloud Platform

在此版本中，您可以将备份目标设置为 Google Cloud Platform 存储桶。以前，您只能将备份目标添加到NetApp StorageGRID、Amazon Web Services 和 Microsoft Azure。

https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-backup-destination.html["了解有关配置BlueXP ransomware protection设置的更多信息"]。



[[support-for-google-cloud-platform]]
=== 支持 Google Cloud Platform

该服务现在支持适用于 Google Cloud Platform 的Cloud Volumes ONTAP进行存储保护。此前，该服务仅支持适用于 Amazon Web Services 和 Microsoft Azure 的Cloud Volumes ONTAP以及本地 NAS。

https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["了解BlueXP ransomware protection以及支持的数据源、备份目标和工作环境"] 。



[[role-based-access-control]]
=== 基于角色的访问控制

您现在可以使用基于角色的访问控制 (RBAC) 限制对特定活动的访问。  BlueXP ransomware protection使用BlueXP的两个角色： BlueXP帐户管理员和非帐户管理员（查看者）。

有关每个角色可以执行的操作的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-roles.html["基于角色的访问控制权限"]。
