= 启用数据分类并扫描个人身份信息 (PII)
:allow-uri-read: 




=== 启用数据分类并扫描个人身份信息 (PII)

在此版本中，您可以启用BlueXP classification（ BlueXP系列的核心组件）来扫描和分类文件共享工作负载中的数据。对数据进行分类可以帮助您识别数据是否包含个人信息或私人信息，这可能会增加安全风险。此过程还会影响工作负载的重要性，并帮助您确保使用适当的保护级别来保护工作负载。

部署了BlueXP classification的客户通常可以在BlueXP ransomware protection中扫描 PII 数据。  BlueXP classification作为BlueXP平台的一部分提供，无需额外付费，并且可以在本地或客户云中部署。

要启动扫描，请在 Protection 页面上，在 Protection 仪表板的 Privacy exposure 列中选择 *Identify exposure*。有关详细信息，请参见 https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-classify.html["使用 BlueXP classification 扫描个人可识别的敏感数据"]。



=== SIEM 与 Microsoft Sentinel 集成

现在，您可以使用 Microsoft Sentinel 将数据发送到安全和事件管理系统 (SIEM) 以进行威胁分析和检测。以前，您可以选择 AWS Security Hub 或 Splunk Cloud 作为您的 SIEM。

https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html["了解有关配置BlueXP ransomware protection设置的更多信息"]。



=== 立即免费试用 30 天

随着此版本的发布， BlueXP ransomware protection的新部署现在有 30 天的免费试用期。此前， BlueXP ransomware protection提供 90 天的免费试用。如果您已享受 90 天免费试用，则该优惠将持续 90 天。
