= 支持Amazon FSx for NetApp ONTAP
:allow-uri-read: 




=== 支持Amazon FSx for NetApp ONTAP

此版本支持Amazon FSx for NetApp ONTAP 。此功能可帮助您使用BlueXP ransomware protection来保护 FSx for ONTAP工作负载。

FSx for ONTAP是一项完全托管的服务，可在云中提供NetApp ONTAP存储的强大功能。它提供与您在本地使用的相同的功能、性能和管理能力，同时具有原生 AWS 服务的灵活性和可扩展性。

BlueXP ransomware protection工作流程进行了以下更改：

* Discovery 包括 FSx for ONTAP 9.15 工作环境中的工作负载。
* “保护”选项卡显示 FSx for ONTAP环境中的工作负载。在这种环境中，您应该使用 FSx for ONTAP备份服务执行备份操作。您可以使用BlueXP ransomware protection快照恢复这些工作负载。
+

TIP: 无法在BlueXP中设置在 FSx for ONTAP上运行的工作负载的备份策略。  Amazon FSx for NetApp ONTAP中设置的任何现有备份策略均保持不变。

* 警报事件展示了新的 FSx for ONTAP工作环境。


有关详细信息，请参阅 https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["了解BlueXP ransomware protection和工作环境"]。

有关受支持选项的信息，请参阅 https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-limitations.html["BlueXP ransomware protection的局限性"]。



=== 需要BlueXP访问角色

您现在需要以下访问角色之一来查看、发现或管理BlueXP ransomware protection：组织管理员、文件夹或项目管理员、勒索软件保护管理员或勒索软件保护查看器。

https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["了解所有服务的BlueXP访问角色"^] 。
